SUPABASE_URL = "https://twrtwgxuwycwmrlndkol.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3cnR3Z3h1d3ljd21ybG5ka29sIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Mjg5NzA1NiwiZXhwIjoyMDU4NDczMDU2fQ.i3kLKtazvyfEoDot59FmNKfzrNeaUTjwhXnBS61wFwU"
ADMIN_PASSWORD = "faieq"